import React from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
// Date Modified: 2026-07-19 09:19
import { articles, photos, profile, projects, services, socials } from './content'

const Arrow = () => <span className="arrow" aria-hidden="true">↗</span>
const emailLink = 'https://wa.me/8801633146887'

function Header() { const [open,setOpen]=React.useState(false); return <><header className="site-header"><a className="brand" href="#hero">{profile.name}<i>✦</i></a><nav><a href="#work">Work</a><a href="#services">Services</a><a href="#writing">Writing</a><a href="#about">About</a></nav><a className="header-cta" href={emailLink}>Start a project <Arrow/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">☰</button></header>{open&&<nav className="mobile-nav"><a href="#work">Work</a><a href="#services">Services</a><a href="#writing">Writing</a><a href="#about">About</a><a href="#contact">Contact</a></nav>}</> }
const socialLabels={facebook:'Facebook',linkedin:'LinkedIn',whatsapp:'WhatsApp',github:'GitHub'}
function SocialIcon({name}){return <span aria-hidden="true">{{facebook:'f',linkedin:'in',whatsapp:'◔',github:'⌘'}[name]}</span>}
function Footer(){return <footer className="footer"><div className="wrap footer-main"><div><p>Have a project in mind?</p><a className="footer-cta" href="#contact">Let's make it memorable <Arrow/></a></div><div className="social-area"><p>Find me online</p><div className="social-links">{Object.entries(socials).map(([name,url])=><a key={name} className={!url?'pending':''} href={url||'#contact'} target={url?'_blank':undefined} rel={url?'noreferrer':undefined} title={url?socialLabels[name]:`Add your ${socialLabels[name]} link in src/content.js`} aria-label={socialLabels[name]}><SocialIcon name={name}/></a>)}</div></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {profile.name}</span><span>Images: Unsplash · Designed with care.</span></div></footer>}
function Eyebrow({children}){return <span className="eyebrow">{children}</span>}
function PageIntro({kicker,title,text}){return <section className="page-intro wrap"><Eyebrow>{kicker}</Eyebrow><h1 dangerouslySetInnerHTML={{__html:title}}/><p>{text}</p></section>}
function ArticleCard({article}){return <a className="article-card" href={`#/article/${article.slug}`}><img src={article.image.src} alt={article.image.alt}/><div className="article-card-copy"><span>{article.category} · {article.readTime}</span><h3>{article.title}</h3><p>{article.excerpt}</p><b>Read article <Arrow/></b></div></a>}
function Marquee(){const items=[...services.map(s=>s.title),...services.map(s=>s.title)];return <div className="marquee"><div>{items.map((t,i)=><><span key={i}>{t}</span><b key={i+'d'}>✦</b></>)}</div></div>}
function ServiceSlider(){const [index,setIndex]=React.useState(0);const service=services[index];const current=String(index+1).padStart(2,'0');const total=String(services.length).padStart(2,'0');return <section className={`service-slider ${service.color}`}><div className="wrap"><div className="service-count">{current} — {total}</div><div className="service-stage"><span>{service.no}</span><div><h2>{service.title}</h2><p>{service.text}</p><a href="#contact" className="text-link">Talk about your project <Arrow/></a></div><div className="slider-controls"><button onClick={()=>setIndex((index+services.length-1)%services.length)} aria-label="Previous service">←</button><button onClick={()=>setIndex((index+1)%services.length)} aria-label="Next service">→</button></div></div><div className="slider-dots">{services.map((_,i)=><button key={i} className={i===index?'on':''} onClick={()=>setIndex(i)} aria-label={`Show service ${i+1}`}/>)}</div></div></section>}
function Cta(){return <section className="cta"><div className="wrap"><Eyebrow>HAVE A PROJECT IN MIND?</Eyebrow><h2>Bring the spark.<br/><em>I'll bring the structure.</em></h2><a className="button light" href="#contact">Start a conversation <Arrow/></a></div></section>}

function Landing(){
  const [ci,setCi]=React.useState(0);
  const collageProjects=projects.slice(0,6);
  React.useEffect(()=>{const t=setInterval(()=>setCi(c=>(c+1)%collageProjects.length),3500);return()=>clearInterval(t)},[collageProjects.length]);
  return <><section id="hero" className="hero wrap"><Eyebrow><i className="live-dot"/> Available for selected work</Eyebrow><h1>Websites that make<br/><em>an entrance.</em></h1><p>{profile.intro}</p><div className="hero-actions"><a className="button dark" href="#work">Explore the work <Arrow/></a><a className="text-link" href="#contact">Let's work together</a></div><div className="hero-collage">{collageProjects.map((p,i)=><img key={i} src={p.image.src} alt={p.title} className={i===ci?'on':''}/>) }<span className="bubble peach">WordPress<br/>with soul</span><span className="bubble lemon">React<br/>energy</span><span className="star">✦</span></div></section>
  <Marquee/>
  <section id="focus" className="wrap split-section"><Eyebrow>01 / THE FOCUS</Eyebrow><div><h2>Sharp thinking.<br/><em>Vivid execution.</em></h2><p>From the first structure to the last interaction, every choice should make a website easier to understand, more enjoyable to explore, and more useful to the people behind it.</p><a href="#services" className="text-link">Check my services <Arrow/></a></div></section>
  <section id="writing-preview" className="home-writing wrap"><div className="section-top"><div><Eyebrow>02 / FROM THE NOTEBOOK</Eyebrow><h2>Useful ideas for<br/><em>better websites.</em></h2></div><a href="#writing" className="text-link">See all articles <Arrow/></a></div><div className="article-grid">{articles.slice(0,2).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section>
  <section className="gallery-band"><div className="gallery-track">{projects.map((p,i)=><img key={i} src={p.image.src} alt={p.title}/>)}</div></section>
  <section id="work"><PageIntro kicker="SELECTED WORK / 03" title="Real work deserves<br/><em>the spotlight.</em>" text="A selection of live websites I have built. Each one is a real site, owned by a real client. Contact me to check more projects!!"/><section className="wrap work-gallery">{projects.map((p,i)=><a className="project-card" key={p.slug} href={p.url} target="_blank" rel="noreferrer"><div className="project-img"><img src={p.image.src} alt={p.image.alt}/><span className="project-number">0{i+1}</span></div><div className="project-copy"><h3>{p.title}</h3><p>{p.outcome}</p><span className="project-link">Visit website <Arrow/></span>{p.note&&<small>{p.note}</small>}</div></a>)}</section><section className="wrap process"><Eyebrow>THE CASE-STUDY FRAMEWORK</Eyebrow><div className="process-grid">{['The context','The challenge','The approach','The outcome'].map((x,i)=><div key={x} className="process-card"><div className="process-card-inner"><span className="process-num">0{i+1}</span><h3>{x}</h3><p>{['What the organisation needed and who the website serves.','The practical problem the new site needed to solve.','The design, WordPress, or front-end choices that mattered.','What changed: clearer content, a stronger experience, or easier editing.'][i]}</p></div></div>)}</div></section></section>
  <section id="services"><PageIntro kicker="SERVICES / 04" title="Make the digital<br/><em>feel human.</em>" text="I bring structure, visual direction, and thoughtful front-end execution to websites that need to communicate with confidence."/><section className="wrap services-list">{services.map(s=><article className={s.color} key={s.no}><span>{s.no}</span><h2>{s.title}</h2><p>{s.text}</p><a href="#contact">Enquire about this <Arrow/></a></article>)}</section><section className="wrap principles"><Eyebrow>WHAT GUIDES THE WORK</Eyebrow><h2>Clear over clever.<br/>Useful over noisy.<br/><em>Memorable by design.</em></h2><div className="principles-inner"><div className="principles-text" style={{maxWidth:'560px'}}><p>I believe the best web work is built on restraint and intention. Every line of copy, every layout choice, and every interaction should earn its place by making the experience clearer, more useful, or more human. That is the standard I bring to every project. A website should feel like a well-organized room: everything has a place, nothing competes for attention without purpose, and visitors can move through it without confusion. I prioritize clarity over decoration, functionality over trend, and long-term maintainability over quick fixes. Every design decision is weighed against what the user actually needs, not just what looks impressive in a portfolio screenshot. The result is work that ages gracefully, performs reliably, and serves the people who use it every day.</p></div><div className="principles-image"><img src={photos[2].src} alt={photos[2].alt}/></div></div></section></section>
  <section id="about"><PageIntro kicker="ABOUT / 05" title="A considered web<br/><em>is a kinder web.</em>" text="Good digital work respects attention. It gives people a clear path, gives teams tools they can use, and leaves room for a little delight."/><section className="wrap about-story"><img src={photos[1].src} alt="Design notes and laptop on a desk"/><div><Eyebrow>THE APPROACH</Eyebrow><h2>Purpose first.<br/>Pixels second.</h2><p>I believe websites work hardest when strategy, words, design, and development are pulling in the same direction. The aim is never decoration for its own sake—it is a digital home people understand and remember.</p><p>{profile.role}, based in {profile.location}.</p></div></section><section className="beliefs"><div className="wrap"><Eyebrow>THE NON-NEGOTIABLES</Eyebrow>{['Make the next step obvious.','Leave editors in control.','Respect every screen size.','Give every detail a reason.'].map((b,i)=><p key={b}><span>0{i+1}</span>{b}</p>)}</div></section></section>
  <section id="contact"><section className="contact-hero wrap"><Eyebrow>CONTACT / 06</Eyebrow><h1>Let's make<br/><em>something bright.</em></h1><p>Share a little about your website, what needs to change, and what a useful outcome looks like. I'll have a thoughtful look.</p><a className="button dark" href={emailLink}>Start a conversation <Arrow/></a><span className="contact-spark">✦</span></section><section className="wrap contact-note"><h2>Before you send</h2><p>Include the kind of website you need, its audience, the most important goal, and your ideal timing. A few useful details make a stronger first conversation.</p>{!profile.email&&<small>Add your email in <code>src/content.js</code> to activate the contact link before publishing.</small>}</section></section>
  <section id="writing"><PageIntro kicker="WRITING / 07" title="Notes for making<br/><em>the web better.</em>" text="Practical editorial pieces on WordPress development, React interfaces, content structure, and the decisions that give a website staying power."/><section className="wrap all-articles">{articles.map(a=><ArticleCard key={a.slug} article={a}/>)}</section></section>
  <Cta/>
  <Footer/>
</>;
}

function Article({article}){React.useEffect(()=>{if(!article)return;document.title=`${article.title} — ${profile.name}`;const schema=document.createElement('script');schema.type='application/ld+json';schema.id='article-schema';schema.text=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.excerpt,datePublished:'2026-07-01',author:{'@type':'Person',name:profile.name},image:article.image.src});document.head.appendChild(schema);return()=>{document.getElementById('article-schema')?.remove();document.title=`${profile.name} — WordPress Developer & Digital Experience Designer`}},[article]);if(!article)return <NotFound/>;const related=articles.filter(item=>item.slug!==article.slug).slice(0,2);return <><article className="article"><div className="wrap"><a className="back" href="#writing">← All writing</a><div className="article-hero"><img src={article.image.src} alt={article.image.alt}/><div><Eyebrow>{article.category} · {article.readTime}</Eyebrow><h1>{article.title}</h1><p>{article.excerpt}</p><small>{article.date}</small></div></div><div className="article-layout"><aside className="article-sidebar"><div className="side-card"><span>IN THIS ARTICLE</span><ol>{article.body.map(([heading],index)=><li key={heading}><a href={`#section-${index+1}`} onClick={(e)=>{e.preventDefault();document.getElementById(`section-${index+1}`)?.scrollIntoView({behavior:'smooth'})}}>{heading}</a></li>)}</ol></div><div className="author-card"><div className="author-mark">S<span>✦</span></div><div><span>WRITTEN BY</span><b>{profile.name}</b><p>{profile.role}</p></div></div><div className="side-share"><span>SHARE THE IDEA</span><div><a href="#contact" aria-label="Share on LinkedIn">in</a><a href="#contact" aria-label="Share on Facebook">f</a><a href="#contact" aria-label="Share on WhatsApp">◔</a></div></div></aside><div className="article-body">{article.body.map(([h,p],index)=><section id={`section-${index+1}`} key={h}><span className="article-number">0{index+1}</span><h2>{h}</h2><p>{p}</p>{index===1&&<aside>Good websites feel straightforward because the ...</aside>}</section>)}</div></div></div></article><Footer/></>}
function NotFound(){return <><PageIntro kicker="NOT FOUND" title="This page took<br/><em>a scenic route.</em>" text="The page you are looking for is not here, but the rest of the site is waiting."/><div className="wrap"><a className="button dark" href="#/">Return home <Arrow/></a></div><Footer/></>}
function App(){if(location.hash.startsWith('#/article/')) return <><Header/><Article article={articles.find(a=>a.slug===location.hash.slice(9))}/></>;return <><Header/><Landing/></>}
createRoot(document.getElementById('root')).render(<App/>)
