export const profile = {
  name: 'Shohan',
  role: 'WordPress developer & digital experience designer',
  location: 'Bangladesh · Working worldwide',
  email: '',
  intro: 'I create thoughtful WordPress and front-end experiences that give good ideas a clear, memorable place to live.',
}

// Paste your real profile links here before publishing. WhatsApp accepts a full wa.me URL.
export const socials = { facebook: 'https://www.facebook.com/bossshohan', linkedin: 'https://www.linkedin.com/in/zahid-hasan-9969211a9/' }

export const services = [
  { no: '01', title: 'WordPress Websites', text: 'Custom, responsive WordPress websites built around your content, brand, and the practical needs of the people who will manage them.', color: 'coral' },
  { no: '02', title: 'Elementor Websites', text: 'Flexible Elementor websites with a well-structured design system, useful templates, and an editor experience that stays easy to use.', color: 'lemon' },
  { no: '03', title: 'Figma to WordPress', text: 'Thoughtful Figma-to-WordPress implementation that protects the intended layout, interactions, responsiveness, and content hierarchy.', color: 'mint' },
  { no: '04', title: 'PSD to WordPress', text: 'Pixel-conscious WordPress builds from PSD layouts, translated into modern, responsive pages that work smoothly across devices.', color: 'coral' },
  { no: '05', title: 'Adobe XD to WordPress', text: 'Adobe XD designs developed into dependable WordPress websites with clear components and maintainable page-building tools.', color: 'lemon' },
  { no: '06', title: 'MERN Development with AI', text: 'Custom MERN applications enhanced with practical AI-powered features, built around a focused user flow and a reliable front end.', color: 'mint' },
  { no: '07', title: 'WordPress Automation using Python', text: 'Python-powered WordPress automation for repetitive publishing, content operations, and workflow tasks that deserve a faster, safer process.', color: 'coral' },
]

export const projects = [
  {
    title: "Safeaviation",
    slug: "safeaviation",
    url: "https://safeaviation.com.bd/",
    image: { src: "./projects-ss/safe-aviation.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. Fully responsive across all screen sizes with clean content management.",
  },
  {
    title: "Vueltaymediabcn",
    slug: "vueltaymediabcn",
    url: "https://vueltaymediabcn.com/",
    image: { src: "./projects-ss/vueltaymedia.png" },
    role: "Full site build",
    outcome: "Built with Elementor Pro and Crocoblock JetEngine. A vibrant responsive brand site with structured content blocks.",
  },
  {
    title: "Enoboxexperiencias",
    slug: "enoboxexperiencias",
    url: "https://enoboxexperiencias.com/",
    image: { src: "./projects-ss/enobox.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs, powered by Crocoblock JetEngine. A fully responsive experience site with polished layouts and clean editing.",
  },
  {
    title: "Falken Umzuege",
    slug: "falken-umzuege",
    url: "https://falken-umzuege.de/",
    image: { src: "./projects-ss/falken.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs, powered by Crocoblock JetEngine. A responsive logistics site with clear service pages and structured content.",
  },
  {
    title: "Sindromealienacionparental",
    slug: "sindromealienacionparental",
    url: "https://sindromealienacionparental.com/",
    image: { src: "./projects-ss/bastida.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A sensitive informational site delivered with responsive design and clean content management.",
  },
  {
    title: "Detweedejeugd",
    slug: "detweedejeugd",
    url: "https://detweedejeugd.nl/",
    image: { src: "./projects-ss/detweede.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A responsive WooCommerce shop-enabled site with structured editorial content.",
  },
  {
    title: "Cremaschinilex",
    slug: "cremaschinilex",
    url: "https://www.cremaschinilex.com/",
    image: { src: "./projects-ss/cremaschinilex.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A fully responsive legal site with structured content management.",
  },
  {
    title: "Ez-roi",
    slug: "ez-roi",
    url: "https://ez-roi.co.il/",
    image: { src: "./projects-ss/ez-roi-co-il.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A responsive business site with custom content blocks and clean editing workflows.",
  },
  {
    title: "Congresgebouwdevereeniging",
    slug: "congresgebouwdevereeniging",
    url: "https://congresgebouwdevereeniging.nl/",
    image: { src: "./projects-ss/congresgebouwdevereeniging.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A fully responsive venue site with structured event and page content.",
  },
  {
    title: "Happyfillers",
    slug: "happyfillers",
    url: "https://happyfillers.nl/",
    image: { src: "./projects-ss/happyfillers.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A responsive staffing site with clear content management.",
  },
  {
    title: "Piggibacks",
    slug: "piggibacks",
    url: "https://piggibacks.com/",
    image: { src: "./projects-ss/piggibacks.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A fully responsive delivery website with structured blocks and clean editing.",
  },
  {
    title: "Sustainablevietnam",
    slug: "sustainablevietnam",
    url: "https://sustainablevietnam.com/",
    image: { src: "./projects-ss/sustainablevietnam.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A responsive sustainability site with structured content for growth.",
  },
  {
    title: "Innovaretailstudio",
    slug: "innovaretailstudio",
    url: "https://innovaretailstudio.com/",
    image: { src: "./projects-ss/innovaretailstudio.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs, powered by Crocoblock JetEngine. A fully responsive studio site with structured content and polished UI.",
  },
  {
    title: "Gizmocraddle",
    slug: "gizmocraddle",
    url: "https://gizmocraddle.com/",
    image: { src: "./projects-ss/gizmocraddle.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs. A responsive WooCommerce experience with custom product content. Under development — client needs to push content.",
    note: "Under development — client needs to push content.",
  },
  {
    title: "Staging2 Innovaretailstudio",
    slug: "staging2-innovaretailstudio",
    url: "https://staging2.innovaretailstudio.com/",
    image: { src: "./projects-ss/staging2-innovaretailstudio.png" },
    role: "Full site build",
    outcome: "Pixel-perfect Elementor Pro build from Figma designs, powered by Crocoblock JetEngine. A responsive staging environment with structured studio content for review.",
  },
  {
    title: "Staging3 Sindromealienacionparental",
    slug: "staging3-sindromealienacionparental",
    url: "https://staging3.sindromealienacionparental.com/",
    image: { src: "./projects-ss/staging3-sindromealienacionparental.png" },
    role: "Full site build",
    outcome: "It was built with elementor pro, from a figma design to pixel perfect website",
  },
]

export const photos = [
  { src: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=85', alt: 'Laptop displaying website analytics' },
  { src: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1400&q=85', alt: 'Hands writing design notes beside a laptop' },
  { src: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?auto=format&fit=crop&w=1400&q=85', alt: 'Computer monitor with code editor' },
  { src: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1400&q=85', alt: 'Mobile website design on a desk' },
]

export const articles = [
  {
    slug: 'wordpress-content-system', category: 'WordPress development', readTime: '8 min read', date: 'July 2026', image: photos[1],
    title: 'How to build a WordPress site your team can actually maintain',
    excerpt: 'The strongest WordPress builds are not just attractive on launch day. They give editors a reliable, flexible system for the work that follows.',
    body: [
      ['Start with the people who will edit', 'A site can look excellent in a design review and still be difficult to update. The most useful early question is not “what can this template do?” but “what will the person maintaining this page need to change next month?” That answer should shape the content model, the block library, and the documentation.'],
      ['Model the content before styling the page', 'Services, team members, locations, resources, and case studies often deserve their own content types because they are reused in different places. When content is structured deliberately, editors update it once and the site can present it consistently wherever it is needed.'],
      ['Create blocks around real editorial jobs', 'A reusable block should solve an actual task: introduce a service, collect frequently asked questions, show a testimonial, or invite an enquiry. Too many near-identical blocks create uncertainty. A smaller library with strong defaults is easier to learn and protects the visual system.'],
      ['Put guardrails in the right places', 'Editors should not have to understand an eight-point spacing scale to make a good page. Provide sensible type, spacing, and image defaults. Keep the options that genuinely matter—such as emphasis, alignment, or a theme variation—and remove options that only make a page inconsistent.'],
      ['Make handover part of delivery', 'A useful handover covers everyday tasks: editing a page, publishing an article, replacing an image, and restoring a revision. A short guide or screen recording gives the site a much longer useful life than a beautiful launch moment alone.'],
    ],
  },
  {
    slug: 'react-interface-performance', category: 'React', readTime: '7 min read', date: 'July 2026', image: photos[2],
    title: 'React interface performance: the design choices visitors notice first',
    excerpt: 'Performance is not only a score. It is the feeling that the interface understands what a visitor wants to do and responds without hesitation.',
    body: [
      ['Make the first screen useful immediately', 'The opening view should establish context, show the primary action, and load its key visual without waiting for every secondary feature. Route-level code splitting and intentional loading priorities make it easier to deliver this essential layer quickly.'],
      ['Design loading states instead of hiding them', 'A stable skeleton, a pressed button state, or a clear progress message answers a visitor’s most basic question: “did that work?” Good feedback is calm and specific. It turns the time the interface needs into a moment that still feels deliberate.'],
      ['Protect the reading position', 'Unexpected layout shifts are one of the quickest ways to make a page feel unreliable. Reserve dimensions for media, keep cards structurally predictable, and avoid inserting late content above what someone is already reading.'],
      ['Use motion to explain, not decorate', 'Small transitions help people understand what changed: a panel opens, a card is selected, a new section becomes available. Motion should have a job and respect reduced-motion preferences. The clearest animation is often the one visitors barely notice.'],
      ['Measure the real route', 'After the experience is defined, use field data and production measurements to locate the largest cost. Images, client-side scripts, and third-party embeds normally offer more meaningful savings than micro-optimising a component that barely affects the page.'],
    ],
  },
  {
    slug: 'website-content-audit', category: 'Content strategy', readTime: '6 min read', date: 'July 2026', image: photos[0],
    title: 'A content audit that makes a website redesign easier',
    excerpt: 'Before a redesign changes the interface, it should clarify what the website is responsible for saying, proving, and helping people do.',
    body: [
      ['Treat every page as a decision', 'A content audit is not only an inventory. For each page, decide whether it earns its place: retain it, rewrite it, merge it, redirect it, or remove it. This is how a redesign becomes simpler rather than just newer.'],
      ['Map intent before navigation', 'Visitors arrive with different questions. A future customer may need evidence and a route to enquire; an existing customer may need help; a candidate may need a view of the culture. Group pages around those needs, then name navigation items in language people recognise.'],
      ['Find the proof', 'Strong pages combine a clear promise with evidence. That evidence may be a process, an example, a result, an answer to a common concern, or a useful explanation. Collect it early so the visual design has real substance to work with.'],
      ['Give search engines a clear job', 'Each important page should answer one focused question with a descriptive title, useful headings, readable copy, and relevant internal links. Search-friendly structure is usually visitor-friendly structure too.'],
    ],
  },
  {
    slug: 'elementor-workflow-for-teams', category: 'WordPress development', readTime: '7 min read', date: 'July 2026', image: photos[1],
    title: 'An Elementor Pro workflow that keeps teams productive',
    excerpt: 'A well-organized Elementor workspace does more than produce good-looking pages. It makes daily editing predictable and reduces the number of questions sent to developers.',
    body: [
      ['Set a shared grid and spacing system', 'Agree on container widths, section padding, and gap scale before anyone starts building. When every editor works from the same system, pages feel consistent without constant rewording or manual alignment adjustments.'],
      ['Use saved templates for repeated patterns', 'Headers, footers, service blocks, and enquiry sections often appear across many pages. Saving them as templates keeps the design coherent and reduces repetitive work while preserving editing freedom.'],
      ['Limit choices to useful ones', 'Too many style options create decision fatigue. Provide sensible defaults for typography, colour, and spacing, and keep only the variations that genuinely matter for the brand or content type.'],
      ['Document the small decisions', 'A short guide that explains naming conventions, image sizes, template locations, and update workflows gives future editors far more confidence than a polished but undocumented site.'],
    ],
  },
  {
    slug: 'design-handoff-that-works', category: 'Design', readTime: '5 min read', date: 'July 2026', image: photos[2],
    title: 'Design handoff that actually works for developers',
    excerpt: 'The gap between a polished Figma file and a pixel-perfect website usually comes from unclear structure, missing states, and assumptions that were never written down.',
    body: [
      ['Organize frames by page and state', 'Developers need the default view, hover states, responsive adjustments, and error or empty states clearly labeled. A single beautiful desktop screen rarely contains enough information for a reliable build.'],
      ['Call out responsive behavior explicitly', 'Show how layouts stack, how navigation collapses, and how typography scales between desktop, tablet, and mobile. Video walkthroughs can explain interactions that are hard to capture in static images.'],
      ['Share tokens, not just colours', 'Font sizes, spacing values, and component behaviour should be treated as design tokens. When developers receive these as concrete values or documentation, implementation becomes faster and more consistent.'],
      ['Keep a shared changelog', 'Design evolves after handoff. A short changelog of accepted revisions helps developers stay aligned and prevents wasted work on outdated layouts or missing components.'],
    ],
  },
  {
    slug: 'maintainable-wordpress-editor-experience', category: 'WordPress development', readTime: '6 min read', date: 'July 2026', image: photos[3],
    title: 'A maintainable WordPress editor experience for non-technical teams',
    excerpt: 'The best WordPress build is not measured by launch day alone. It is measured by how confidently an editor can publish, update, and reorganise content months later.',
    body: [
      ['Start with the editor journey, not the template gallery', 'Before choosing blocks or widgets, map the everyday tasks: adding a testimonial, publishing an event, updating a team member. Then build the system around those tasks rather than around available components.'],
      ['Use custom post types for repeated content', 'Services, locations, case studies, and team members often deserve their own content type. When content is structured this way, editors manage it in one place and the site presents it consistently everywhere it appears.'],
      ['Reduce long confusing forms', 'Break large forms into small steps, hide advanced fields by default, and always provide examples. Simpler forms produce better content and fewer support requests from team members who feel unsure where to start.'],
      ['Build a short, tested handover', 'A useful handover answers the questions editors actually ask: how do I replace this image, how do I move this section, and how do I undo a mistake. A short recorded walkthrough is worth more than a long written manual.'],
    ],
  },
  {
    slug: 'figma-to-pixel-perfect-elementor-website', category: 'WordPress development', readTime: '10 min read', date: 'July 2026', image: { src: '/projects-ss/figma.png', alt: 'Figma to Elementor Pro pixel perfect website workflow' },
    title: 'Figma to Pixel Perfect Elementor Website',
    excerpt: 'Learn how to transform Figma designs into pixel-perfect Elementor Pro websites with this comprehensive step-by-step guide. From design handoff to final deployment, master the art of converting static mockups into fully responsive WordPress sites.',
    body: [
      ['Understanding the Figma to Elementor workflow', 'Converting a Figma design into a live Elementor Pro website requires more than just copying colors and fonts. It demands a systematic approach that preserves the designer\'s intent while leveraging Elementor\'s powerful building blocks. This guide walks you through the complete process, from initial design analysis to final quality assurance.'],
      ['Preparing your Figma design for development', 'Before opening Elementor, analyze your Figma file thoroughly. Identify the grid system, spacing scale, typography hierarchy, color palette, and component patterns. Export all necessary assets including icons, illustrations, and images in the correct formats and sizes. Document responsive breakpoints and note how layouts should adapt across desktop, tablet, and mobile viewports.'],
      ['Setting up the Elementor environment', 'Configure your WordPress environment with Elementor Pro active. Create a new page and switch to Elementor editor. Set up your global site settings first: establish your brand colors, typography, spacing units, and container widths. This foundation ensures consistency throughout the build and reduces repetitive styling work later.'],
      ['Building the header and navigation', 'Start with the header section using Elementor\'s theme builder or a dedicated header template. Recreate the logo placement, navigation menu, call-to-action buttons, and any mobile menu behavior. Pay attention to hover states, active states, and dropdown behaviors. Ensure the header remains sticky if specified in the design, and test its appearance across all breakpoints.'],
      ['Recreating hero sections and layouts', 'The hero section often contains the most complex visual elements. Use Elementor\'s flexbox and grid containers to match the Figma layout precisely. Implement any background images, gradients, or overlay effects. Add animations sparingly and only where they enhance the user experience. Test text readability and visual hierarchy against the original design.'],
      ['Implementing content sections with precision', 'Work through each content section methodically. Use Elementor\'s inner sections to maintain the grid structure defined in Figma. Apply exact padding, margins, and gap values from your design specifications. For cards and feature blocks, create reusable templates that maintain consistency. Pay special attention to border radii, shadows, and hover effects.'],
      ['Managing typography and readability', 'Match the Figma typography scale exactly in Elementor\'s global typography settings. Configure font families, sizes, line heights, letter spacing, and font weights for each heading level and body text style. Ensure proper contrast ratios for accessibility. Test how typography scales across different screen sizes and adjust using Elementor\'s responsive controls.'],
      ['Optimizing images and media assets', 'Compress all images before uploading to WordPress. Use WebP format where supported and provide fallbacks. Set appropriate image dimensions in Elementor to prevent layout shifts. For background images, use the correct focal points and attachment settings. Implement lazy loading for below-the-fold images to improve page performance.'],
      ['Testing responsive behavior thoroughly', 'Switch between desktop, tablet, and mobile views in Elementor editor at each stage. Verify that layouts stack correctly, images scale appropriately, and text remains readable. Check navigation behavior on mobile devices. Test touch targets for buttons and links to ensure they meet minimum size requirements. Validate that no horizontal scrolling occurs on any device.'],
      ['Quality assurance and pixel-perfect verification', 'Use browser developer tools to compare your Elementor build against the original Figma design side by side. Check spacing, alignment, colors, and typography at multiple screen sizes. Validate HTML structure and accessibility standards. Test all interactive elements, forms, and links. Run performance audits using tools like Google PageSpeed Insights to ensure the site loads quickly.'],
      ['Deployment and maintenance best practices', 'Once the pixel-perfect build is complete, deploy to staging first for final client review. Use Elementor\'s export/import features or a deployment plugin to move the site to production. Document the template structure for future updates. Train content editors on using Elementor while maintaining design consistency. Regularly test the site across browsers and devices after updates.'],
    ],
  },
]


